---
- hosts: all
  connection: local
  vars_files:
    - config.yml

  roles:
    - { role: user-configuration, tags: [user-configuration] }
    - { role: elliotweiser.osx-command-line-tools, tags: [command-line-tools] }
    - { role: geerlingguy.mac.homebrew, tags: [homebrew] }

  tasks:
    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]
