---
- hosts: all
  connection: local
  become: true
  vars_files:
    - config.yml
  roles:
    - {role: user-configuration, tags: [user-configuration]}
    - {role: print-scan, tags: [print-scan]}
    - {role: fonts, tags: [fonts]}
    - {role: emacs, tags: [emacs, emacs-packages]}
    - {role: general-apps, tags: [general-apps]}
    - {role: window-manager, tags: [window-manager]}
    - {role: web-browsers, tags: [web-browsers]}
    - {role: dev-tools, tags: [dev-tools]}
    - {role: docker, tags: [docker]}
  tasks:
  - import_tasks: tasks/clone-projects.yml
    tags: ['clone-projects']
  - import_tasks: tasks/extra-packages.yml
    tags: ["extra-packages"]
