* kwame-dat/dev-machine-playbook
Uses [[https://www.ansible.com/][Ansible]] to provision and setup my development machine from scratch so I
don't have to do things manually.

I personally enjoy working on a arch based Linux distribution. However from time
to time I come across situation where I need to work on Ubuntu, MacOs or WSL.

Hence I plan to support the following Operating Systems;
- [X] [[https://arcolinux.com/][ArcoLinux (Arch Linux)]]
- [X] [[https://www.apple.com/uk/macos/big-sur/][MacOs]]
- [X] [[https://ubuntu.com/][Ubuntu (Debian)]]
- [X] [[https://docs.microsoft.com/en-us/windows/wsl/install-win10][Windows (WSL Ubuntu 20.04)]]
** Provisioning
*** MacOs
- Ensure Apple's command line tools are installed (xcode-select --install to launch the installer)
  #+begin_src bash
    xcode-select --install
  #+end_src
- Install [[https://docs.ansible.com/ansible/latest/installation_guide/index.html][Ansible]]
  - Run the following command below to add Python 3 to your $PATH:
    #+begin_src conf
      export PATH="$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:$PATH"
    #+end_src
  - Upgrade Pip:
    #+begin_src bash
      sudo pip3 install --upgrade pip
    #+end_src
  - Install Ansible:
    #+begin_src bash
      pip3 install ansible
    #+end_src
- Clone or download this repository to your local drive.
  #+begin_src bash
    git clone https://github.com/kwame-dat/dev-machine-playbook.git
  #+end_src
- Run the command below inside cloned directory to install required Ansible roles
  #+begin_src bash
    ansible-galaxy install -r requirements.yml
  #+end_src
- Provision
  #+begin_src bash
    ansible-playbook main-macos.yml -i inventory
  #+end_src

*** Arch
- Install ansible 
  #+begin_src bash
    sudo pacman -S ansible
  #+end_src
- Install dependecies
  #+begin_src bash
    ansible-galaxy install -r requirements.yml
  #+end_src
- Provision
  #+begin_src bash
    ansible-playbook main-arch.yml -i inventory
  #+end_src
*** Ubuntu
- Install ansible
  #+begin_src bash
    sudo apt install ansible -y
  #+end_src
- Install dependecies
  #+begin_src bash
    ansible-galaxy install -r requirements.yml
  #+end_src
- Provision
  #+begin_src bash
    ansible-playbook main-ubuntu.yml -i inventory
  #+end_src
*** Window WSL2 Ubuntu
- Install ansible
  #+begin_src bash
    sudo apt install ansible -y
  #+end_src
- Install dependecies
  #+begin_src bash
    ansible-galaxy install -r requirements.yml
  #+end_src
- Provision
  #+begin_src bash
    ansible-playbook main-wsl-ubuntu.yml -i inventory
  #+end_src
** Development
*** Prerequisite
- vagrant
- virtualbox
