---
- name: Clone Personal Repo
  become: false
  ansible.builtin.git:
    repo: "git@github.com:tonyampomah/{{ item }}.git"
    dest: "~/Repo/{{ item }}"
    clone: yes
    update: yes
  with_items: "{{ repo }}"

- name: Clone Arksolutions.it Repo
  become: false
  ansible.builtin.git:
    repo: "git@github.com:arksolutions-it/{{ item }}.git"
    dest: "~/Repo/{{ item }}"
    clone: yes
    update: yes
  with_items: "{{ repo_arksolutions_it }}"
