---
window_manager_packages:
  - {name: hyprland, state: present}
  - {name: hyprsunset, state: present}
  - {name: hyprpolkitagent, state: present}
  - {name: hyprpaper, state: present}
  - {name: xdg-desktop-portal-hyprland, state: present}
  - {name: xdg-desktop-portal-gtk, state: present}
  - {name: nwg-look, state: present}
  - {name: fuzzel, state: present}
  - {name: swaybg, state: present}
  - {name: swaybg, state: present}
  - {name: acpi, state: present}
  - {name: blueman, state: present}
  - {name: brightnessctl, state: present}
  - {name: gammastep, state: present}
  - {name: grim, state: present}
  - {name: pavucontrol, state: present}
  - {name: playerctl, state: present}
  - {name: slurp, state: present}
  - {name: surfraw, state: present}
  - {name: sysstat, state: present}
  - {name: waybar, state: present}
  - {name: waydroid, state: present}
  - {name: wl-clipboard, state: present}
  - {name: wlogout, state: present}
  - {name: wofi, state: present}
  - {name: xbindkeys, state: present}
  - {name: network-manager-applet, state: present}
