---
- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

- name: Install fonts
  package:
    name: "{{ item.name }}"
    state: "{{ item.state}}"
  with_items: "{{ fonts_packages }}"
